<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Total</name>
   <tag></tag>
   <elementGuidId>9b676f2a-7d96-49fa-93ab-3c113735935d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cart-summary-row-total ')]//*[(name() = 'div') and (position() = 1)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.cart-summary-row-total div:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be3abb43-560b-44ce-8c5f-9c9a8f11dcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-5</value>
      <webElementGuid>5c699799-6a67-4a76-8cb8-56bf6f237a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total</value>
      <webElementGuid>01d8b3e1-6f56-4d0f-80d9-a151136ead33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c4b2b4cb7bdc53492c9191eebe81b45d</value>
      <webElementGuid>5bb31688-1c1e-4d3e-b0af-94ff570642d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cart-summary-row-total ')]//*[(name() = 'div') and (position() = 1)]</value>
      <webElementGuid>faafe93b-3480-470d-98e6-c89133075ef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cart-summary-row-total ')]//*[(name() = 'div') and (position() = 1)]</value>
      <webElementGuid>8709e68f-3332-43a7-9a35-c60f5dc2a62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Total' or . = 'Total')]</value>
      <webElementGuid>2b94b240-5638-4bfc-b060-1542c2147632</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
