<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input_quantity_2</name>
   <tag></tag>
   <elementGuidId>693479ba-9678-4c41-bbfb-296b94042795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' product-entry ') and (position() = 10)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' js-update-entry-quantity-input ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.product-entry:nth-child(10) .js-update-entry-quantity-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>286b6eaa-bbf0-4a0c-aff9-f634d047ecff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5788f60b-6f31-4582-8c90-7539e837a0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-update-entry-quantity-input pd-update-qty-dropdown-input</value>
      <webElementGuid>da5f43bd-ee03-4f6f-b1a4-8b672a15f083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>9eb00402-3822-4dbd-bbfc-cf611c176393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>604</value>
      <webElementGuid>24f319a8-70e1-429b-b73a-daca16b6e969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6d595a72-6ea5-4ba1-a27f-bd9e7dd7ac54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_quantity_2</value>
      <webElementGuid>bd4a756c-29fa-4bde-9267-b8c9b0b487dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d59066a2-5bd9-45ef-a962-b527f4a4e909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a74bb2b5-4829-4f56-b80d-1b3342b1c2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-51c291dddc1786536fae3588e9269de9</value>
      <webElementGuid>a6546601-ffd4-41e7-a04e-a8f40e145c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' product-entry ') and (position() = 10)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' js-update-entry-quantity-input ')]</value>
      <webElementGuid>3691cfa5-6a55-43c7-af09-47c70a6331fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' product-entry ') and (position() = 10)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' js-update-entry-quantity-input ')]</value>
      <webElementGuid>e6733b59-e2d9-496d-a835-10519a23aaf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_quantity_2']</value>
      <webElementGuid>c1d94f5e-37fd-4bb9-aef4-036012fe3d10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
