<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_js_search_button</name>
   <tag></tag>
   <elementGuidId>178318ea-2c84-42f8-82ac-bf4f119996b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'js_search_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#js_search_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2df40ac-5331-4583-a573-05ded5fde717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link js_search_button</value>
      <webElementGuid>c3f6f6e2-e574-49ca-8284-43216b9ebcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js_search_button</value>
      <webElementGuid>fb8bb3f0-0b1a-4ccf-b3f9-12aa8758a218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c14ed65a-abbd-4ef7-8766-5f1ac65b445d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>9642389f-11c3-4000-9832-5201b3cce95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-017e84054db0916c58066a4136138b83</value>
      <webElementGuid>b90768aa-7339-431a-8269-3f4d69a8fcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'js_search_button']</value>
      <webElementGuid>e0401972-07a5-4732-bdc9-c9f675f418be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'js_search_button']</value>
      <webElementGuid>cfdfe662-cf28-496e-a3db-70138980f928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'js_search_button' and @type = 'submit']</value>
      <webElementGuid>07e4aebc-b9c5-4998-aa2f-a9301c87d00d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
