<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_js_search_button</name>
   <tag></tag>
   <elementGuidId>0ffa4e99-a253-4ea5-a0df-f884f0c34f14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'js_search_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#js_search_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54b4722e-cb64-4bf4-a334-e43c86efb25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link js_search_button</value>
      <webElementGuid>7c70dff5-4512-405a-be55-85ecbb61ac65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js_search_button</value>
      <webElementGuid>042f03f2-03d0-4ab0-a1ab-782bb498ec99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6508b101-1447-42b4-8a17-6a7672d3d3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>e800230d-5e36-4bc1-97d8-804dfcf66011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-017e84054db0916c58066a4136138b83</value>
      <webElementGuid>98c3dca7-3f97-4bbe-8b39-9c252c051389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'js_search_button']</value>
      <webElementGuid>4323fa96-ab48-49ee-ac08-d104f5da9745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'js_search_button']</value>
      <webElementGuid>e06b9adc-3a69-4401-99f9-730c93da4a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'js_search_button' and @type = 'submit']</value>
      <webElementGuid>97c84c68-91d6-45b5-a6e7-2f9dc03c9f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
