<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Correo electrnico</name>
   <tag></tag>
   <elementGuidId>2f4eb283-d4ee-4d86-8d50-077dee3a7952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'usernamelogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#usernamelogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d924874d-51f6-41c1-9faf-add3a2049823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usernamelogin</value>
      <webElementGuid>91565f03-db0e-4e48-b5a2-1f19403f663d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_username</value>
      <webElementGuid>eac7be97-de2e-4ea7-a787-0738e92ba1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-material font-medium  d-block w-100</value>
      <webElementGuid>8126e875-a75c-40f7-8e1b-e9c1d8697680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z0-9]{2,}$</value>
      <webElementGuid>aa2bbc14-694c-4968-965e-e5714ed28ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4fa6e861-407b-4e8f-ab4b-61cb061c8e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>064bfeb2-889e-4d0d-869f-fd5aca59cd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>usernamelogin-list</value>
      <webElementGuid>b4bb481f-6ffd-4c21-ae43-6e907c2f3993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>05a2d3d7-b0bd-4ebe-b956-709147deb159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0fd10ca-a315-48a7-b8d0-2c59c3217323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>04eb015a-1c18-45f4-97d2-f77824da93b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4dc72ec293b2ac8332e66cd3246c228a</value>
      <webElementGuid>66414795-1a09-4f86-aae1-20786c52f1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'usernamelogin']</value>
      <webElementGuid>5b8323ba-dfc1-4acf-a4e4-a7a6b55d7d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'usernamelogin']</value>
      <webElementGuid>041779a2-3f97-4b10-b400-22c9613709ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'usernamelogin' and @name = 'j_username' and @type = 'email']</value>
      <webElementGuid>d516c0b7-05cf-40e1-b8a2-b1ccdd50f832</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
