<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dat-gs-copy1</name>
   <tag></tag>
   <elementGuidId>5ccd5733-76a1-4ac4-b46a-42e659273bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' birthday-input ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.birthday-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a147b342-b48c-4fa3-bdfb-6e7a92bacc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dat-gs-copy1</value>
      <webElementGuid>7dd8579c-433c-4f81-b9b2-c20c33cf8b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>birthday-input</value>
      <webElementGuid>fa3be674-c93f-4e47-ad38-8edd4f67540a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>a4aa640d-5581-4f44-9055-ed93ee90bde4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthday-gs</value>
      <webElementGuid>bc62a9ef-b98e-48b1-906b-dd2cf9257434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(0[1-9]|1[012])[-/.](0[1-9]|[12][0-9]|3[01])[-/.](19|20)\d\d$</value>
      <webElementGuid>a425c60e-580f-4ccb-bf33-86d59472893a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-453be08660b66dac60a08c5d2b1ce3af</value>
      <webElementGuid>d9cd3169-6247-41f6-bbde-92b2b850ddf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' birthday-input ')]</value>
      <webElementGuid>0df86686-a23c-4a7e-a3bf-82ac7a75256b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' birthday-input ')]</value>
      <webElementGuid>4f1d419f-5052-4a3f-bb79-1672af26b59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dat-gs-copy1' and @name = 'birthday-gs']</value>
      <webElementGuid>636d891a-b4df-4914-8ec9-4d5482bc1059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
