<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continuar comprando</name>
   <tag></tag>
   <elementGuidId>c77a2a29-a7c6-4be0-a920-748ad03c2701</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/officedepot/en/']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/officedepot\/en\/&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c0162458-6d93-4ca5-a8f2-c68de1cfbd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; searchAgain();</value>
      <webElementGuid>376f6073-fdbe-4797-8d65-8c65c9a68d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button404</value>
      <webElementGuid>88a80707-1096-4ddc-be90-756d55a7da81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/officedepot/en/</value>
      <webElementGuid>b9aca57f-40ee-419e-a46d-db3899d824e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar comprando</value>
      <webElementGuid>e3576588-2ca7-41dd-8e05-20fe8dad85b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f5130b07473631b58ceafcf9011b3f58</value>
      <webElementGuid>a7d0cd3a-c5fb-43f7-ab26-609743000045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/officedepot/en/']</value>
      <webElementGuid>98079ceb-da54-465f-a4e3-7ab5f47b6c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/officedepot/en/']</value>
      <webElementGuid>497067e0-b845-4bbd-9e48-7ca6a2606524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/officedepot/en/' and (text() = 'Continuar comprando' or . = 'Continuar comprando')]</value>
      <webElementGuid>7d32e312-de5e-459b-a9f0-ffb738dade9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
