<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hola</name>
   <tag></tag>
   <elementGuidId>5a564434-d96c-4848-b4de-a17de7161b58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class and contains(concat(' ', normalize-space(@class), ' '), ' text_mc ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text_mc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87596388-7177-41b3-855c-646df6efbc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_mc</value>
      <webElementGuid>21a3112c-425f-46bb-9245-bb188cf3b946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hola,</value>
      <webElementGuid>e36a7f2e-838e-4fb5-b5bf-639e79173841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a2466535db3cd59ac8a7cc9e0ebf4255</value>
      <webElementGuid>a87c2e88-6836-44c0-a923-441b65c542b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class and contains(concat(' ', normalize-space(@class), ' '), ' text_mc ')]</value>
      <webElementGuid>c6e138d8-608b-4a10-bf81-b087217bb51d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@class and contains(concat(' ', normalize-space(@class), ' '), ' text_mc ')]</value>
      <webElementGuid>f4faff2e-1730-4c26-a1be-ba88d1f31ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hola,' or . = 'Hola,')]</value>
      <webElementGuid>34147986-df43-49b7-9039-b016656cb365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
