<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_sesin</name>
   <tag></tag>
   <elementGuidId>6c95b96e-2f05-4135-8b8a-3257d0d39604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text_mc_bold ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.text_mc_bold</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'sesión' or . = 'sesión')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>a9b86264-940d-4dbe-86f5-f08e196a5d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_mc text_mc_bold</value>
      <webElementGuid>1bc424df-fde0-48f2-ab1e-2cf7491c025e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sesión</value>
      <webElementGuid>be4cb7cc-fa58-416e-9102-6bd2a75cfdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-03fbd123a740b3ea308dc0000d257e78</value>
      <webElementGuid>ea3681b2-fa7d-4377-b0a7-a610f2c3977a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text_mc_bold ')]</value>
      <webElementGuid>562f5e3b-765f-49f3-9dea-3516bb9ca348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text_mc_bold ')]</value>
      <webElementGuid>43071df5-39d8-482f-8616-65e4d5e3b671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'sesión' or . = 'sesión')]</value>
      <webElementGuid>f1c8f9e3-8a21-4d73-91c0-10f43deeed8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
