<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Contrasea</name>
   <tag></tag>
   <elementGuidId>c0156e98-ec8e-4b2b-8a05-793af06dfa4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'j_passwordexpress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#j_passwordexpress</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'j_passwordexpress' and @name = 'j_password' and @type = 'password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6fb8ce5-45ed-4d58-b0b5-255bd95b94ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_passwordexpress</value>
      <webElementGuid>48d839e0-5309-4cb8-ac7e-3fc136ff8b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_password</value>
      <webElementGuid>fc9175e1-5f1d-42f7-9ed5-23df2f1b4b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-material font-medium  d-block w-100</value>
      <webElementGuid>fbec16bb-ef9b-442d-8ebc-53d624102993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{6,}</value>
      <webElementGuid>31d39f2d-2494-4c49-9fa0-b5e58523ac31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b60b7436-56a5-478a-a27b-76ebcc1d4fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>50577d15-2d5a-4be1-9a81-9042ff27dba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>baf160a7-962e-4aca-95d6-62e8cb018c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9f4fc44-1839-41d4-8a37-dcd698c00351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>newpassword</value>
      <webElementGuid>bc22ec2d-7c1a-4710-9b41-2b715eea6894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-46ca71c0e426f7b19bef842cf1895e42</value>
      <webElementGuid>8078819c-28ec-436a-aa5a-6049be08ae77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'j_passwordexpress']</value>
      <webElementGuid>3de3476e-3743-4035-9129-14e07f90d457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'j_passwordexpress']</value>
      <webElementGuid>b27b2f67-a11c-490f-a086-75d5ac8f882f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'j_passwordexpress' and @name = 'j_password' and @type = 'password']</value>
      <webElementGuid>5c8b0b5d-8ae7-494e-9adb-1513d90be61c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
