<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_view-password</name>
   <tag></tag>
   <elementGuidId>5063e8c6-d271-45fd-b929-547abada60f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' view-password ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.view-password</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' view-password ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14652439-c2f2-435e-8ead-a6903a723df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view-password</value>
      <webElementGuid>2556c4d8-f129-4013-9ba8-3b6c194d4646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b6c9de3d3d93eae3566fddafcf3b7173</value>
      <webElementGuid>cb5db14c-13bd-4028-b606-77aeb95f279d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' view-password ')]</value>
      <webElementGuid>358a99f6-98cf-4402-aa72-ee23bd396dcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' view-password ')]</value>
      <webElementGuid>5685698b-debf-4186-be79-e41ea33a412a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
